FROM python:3.10-slim

WORKDIR /app

COPY report/requirements.txt .
COPY report/report.py .
COPY report/report_generator.py .

RUN pip install -r requirements.txt

ENV PYTHONUNBUFFERED=1

EXPOSE 5001

CMD ["python", "report.py"]