FROM gcc:latest

RUN apt-get update && apt-get install -y \
    libasio-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY statistiche/statistiche.cpp .

RUN git clone https://github.com/CrowCpp/Crow.git

RUN g++ -std=c++17 -o app statistiche.cpp -I/app/Crow/include

EXPOSE 5002

CMD ["./app"]